name: 'Deploy All Extensions'
on: 
    workflow_dispatch:

        inputs:
            Publishing_Stategy:
                type: choice
                description: Pick deployment strategy
                options:
                - CD
                - Publish
                required: true
            Environmet_name:
                description: Environment name
                required: true
            Environmet_deployment:
                description: If Publish enter PROD* for production or FAT* for FAT
                required: false

            BusinessCentralLocalization:
                type: boolean
                default: true
            
            TravelOrder:
                type: boolean
                default: true
            
            Manufacturing:
                type: boolean
                default: true
            
            EIN:
                type: boolean
                default: true
            
            HrmPayroll:
                type: boolean
                default: true

            EinLoc:
                type: boolean
                default: true

            Translation:
                type: boolean
            
jobs:

 Create_secrets:
    runs-on: windows-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            lfs: true
        
        - name: Create secrets
          shell: powershell
          run: |
           $deployment = "${{ github.event.inputs.Environmet_deployment }}"
           if ($deployment.StartsWith("PROD") -or $deployment.StartsWith("FAT")) {
            ./script/CreateSecrets.ps1 -Token "${{ secrets.GHTOKENWORKFLOW }}" -Environmet_name "${{ github.event.inputs.Environmet_name }}" -Environmet_deployment $deployment -Publishing_Stategy "${{ github.event.inputs.Publishing_Stategy }}"
           } else {
            ./script/CreateSecrets.ps1 -Token "${{ secrets.GHTOKENWORKFLOW }}" -Environmet_name "${{ github.event.inputs.Environmet_name }}" -Publishing_Stategy "${{ github.event.inputs.Publishing_Stategy }}"
           }

 Initialization:
          needs: [Create_secrets]
          runs-on: [ windows-latest ]
          outputs:
            telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
            environmentsMatrixJson: ${{ steps.DetermineDeploymentEnvironments.outputs.EnvironmentsMatrixJson }}
            environmentCount: ${{ steps.DetermineDeploymentEnvironments.outputs.EnvironmentCount }}
            deploymentEnvironmentsJson: ${{ steps.DetermineDeploymentEnvironments.outputs.DeploymentEnvironmentsJson }}
            deliveryTargetsJson: ${{ steps.DetermineDeliveryTargets.outputs.DeliveryTargetsJson }}
          steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                lfs: true
      
            - name: Initialize the workflow
              id: init
              uses: microsoft/AL-Go-Actions/WorkflowInitialize@v4.0
              with:
                shell: powershell
                eventId: "DO0091"

            - name: Read settings
              id: ReadSettings
              uses: microsoft/AL-Go-Actions/ReadSettings@v4.0
              with:
                  shell: powershell
                  get: type

            - name: Determine Delivery Target Secrets
              id: DetermineDeliveryTargetSecrets
              uses: microsoft/AL-Go-Actions/DetermineDeliveryTargets@v4.0
              with:
                shell: powershell
                checkContextSecrets: 'N'
      
            - name: Read secrets
              id: ReadSecrets
              uses: microsoft/AL-Go-Actions/ReadSecrets@v4.0
              with:
                shell: powershell
                gitHubSecrets: ${{ toJson(secrets) }}
                getSecrets: ${{ steps.DetermineDeliveryTargetSecrets.outputs.ContextSecrets }}
      
            - name: Determine Delivery Targets
              id: DetermineDeliveryTargets
              uses: microsoft/AL-Go-Actions/DetermineDeliveryTargets@v4.0
              env:
                Secrets: '${{ steps.ReadSecrets.outputs.Secrets }}'
              with:
                shell: powershell
                checkContextSecrets: 'Y'

            - name: Determine Deployment Environments
              id: DetermineDeploymentEnvironments
              uses: microsoft/AL-Go-Actions/DetermineDeploymentEnvironments@v4.0
              env:
                GITHUB_TOKEN: ${{ github.token }}
              with:
                shell: powershell
                getEnvironments: '*'
                type: '${{ github.event.inputs.Publishing_Stategy}}'
           
 Deploy:
    needs: [Initialization]
    runs-on:  [ windows-latest ]
    name: Deploy to ${{ github.event.inputs.Environmet_name }}
    environment:
      name: ${{ github.event.inputs.Environmet_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        shell: powershell
        run: |
          $BusinessCentralLocalization=false
          $TravelOrder=false
          $Manufacturing=false
          $EIN=false
          $HrmPayroll=false
          $EinLoc=false
          $Translation=false

          if (${{github.event.inputs.BusinessCentralLocalization}} = 'true'){
            $BusinessCentralLocalization=true
          }
          if (${{github.event.inputs.TravelOrder}} = 'true'){
            $TravelOrder=true
          }
          if (${{github.event.inputs.Manufacturing}} = 'true'){
            $TravelOrder=true
          }
        
          if (${{github.event.inputs.EIN}} = 'true'){
          $EIN=true
          }

          if (${{github.event.inputs.HrmPayroll}} = 'true'){
          $HrmPayroll=true
          }

          
          if (${{github.event.inputs.EinLoc}} = 'true'){
          $EinLoc=true
          }

          if (${{github.event.inputs.Translation}} = 'true'){
          $Translation=true
          }

          ./script/DownloadLatestReleases.ps1 -BusinessCentralLocalization $BusinessCentralLocalization -TravelOrder $TravelOrder -Manufacturing $Manufacturing -EIN $EIN -HrmPayroll $HrmPayroll -EinLoc $EinLoc -Translation $Translation -token ${{ SECRETS.GHTOKENWORKFLOW}}

      - name: Resolve Environment
        id: ResolveEnvironment
        shell: powershell
        run: |
         $EnvOutput = ./script/ResolveEnvironment.ps1 -Publishing_Stategy ${{ github.event.inputs.Publishing_Stategy}} -Environmet_deployment ${{ github.event.inputs.Environmet_deployment}}
         echo "::set-env name=ENV_OUTPUT::$EnvOutput"

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@v4.0
        with:
           shell: powershell
 
      - name: EnvName
        id: envName
        run: |
           $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
           $envName = '${{ github.event.inputs.Environmet_name  }}'
           Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "envName=$envName"
      
      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v4.0
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'AuthContext,${{ github.event.inputs.Environmet_name }}_EnvironmentName,EnvironmentName,projects'

      - name: Deploy
        uses: microsoft/AL-Go-Actions/Deploy@v4.0
        env:
          Secrets: '${{ steps.ReadSecrets.outputs.Secrets }}'
        with:
          shell: powershell
          environmentName: ${{ github.event.inputs.Environmet_name }}
          artifacts: '.artifacts'
          type: '${{ github.event.inputs.Environmet_deployment}}'
          deploymentEnvironmentsJson: ${{ needs.Initialization.outputs.deploymentEnvironmentsJson }}