name: Issue labeler
on:
  issues:
    types: [ opened ]

permissions:
  issues: write
  actions: read
  contents: read

jobs:
  label-component:
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      issues: write

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/BugReport.yml
      - name: Set labels on the issue
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: extension
          block-list: |
            None
            Other
          token: ${{ secrets.GITHUB_TOKEN }}

  add-to-project:
            name: Add issue to project
            runs-on: ubuntu-latest
            steps:
              - uses: actions/add-to-project
                with:
                  project-url: https://github.com/orgs/NPSBeograd/projects/19
                  github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
                  